name: QA to STAGE Code Sync

on:
  workflow_dispatch:
    inputs:
      syncNow:
        description: 'Sync Now'
        required: false

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git identity
        run: |
          git config user.email "actions@github.com"
          git config user.name "Github Actions"

      - name: Fetch latest changes from pricefx-eds-qa
        run: |
          git remote add pricefx-eds-qa https://github.com/pricefx/pricefx-eds-qa
          git fetch pricefx-eds-qa main

      - name: Merge changes excluding fstab.yaml
        run: |
          git checkout main
          git merge --no-ff --no-edit pricefx-eds-qa/main --strategy-option=ours --allow-unrelated-histories
          git rm --cached fstab.yaml
          git commit -m "Sync main branch from pricefx-eds-qa, excluding fstab.yaml"

      - name: Push changes to pricefx-eds-stage
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_PERSONAL_ACCESS_TOKEN }}
          branch: main
