name: STAGE to PROD Code Sync

on:
  workflow_dispatch:
    inputs:
      syncNow:
        description: 'Sync Now'
        required: false

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: pricefx/pricefx-eds-prod
          token: ${{ secrets.GIT_PERSONAL_ACCESS_TOKEN  }}
          ref: main

      - name: Configure Git identity
        run: |
          git config user.email "actions@github.com"
          git config user.name "Github Actions"

      - name: Fetch latest changes from pricefx-eds-stage
        run: |
          git remote add pricefx-eds-stage https://github.com/pricefx/pricefx-eds-stage
          git fetch pricefx-eds-stage main

      - name: Merge changes excluding fstab.yaml
        run: |
          git checkout main
          git merge --no-ff --no-edit pricefx-eds-stage/main --strategy-option=ours --allow-unrelated-histories
          git rm --cached fstab.yaml || true
          git commit -m "Sync main branch from pricefx-eds-stage, excluding fstab.yaml" || true

      - name: Push changes to pricefx-eds-prod
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_PERSONAL_ACCESS_TOKEN }}
          branch: main
